_wandb:
    value:
        cli_version: 0.19.8
        code_path: code/NeatRL/benchmark/Custom/half-cheetah-v2.py
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 55
                - 105
            "2":
                - 1
                - 55
                - 105
            "3":
                - 13
                - 16
                - 23
                - 35
                - 55
            "4": 3.11.11
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
env_id:
    value: HalfCheetah-v5
n_envs:
    value: 16
run:
    value: 1
seed:
    value: 42
total_timesteps:
    value: 1000
